-- add military branches
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Air Force')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Air Force Reserve')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Air National Guard')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Army')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Army Reserve')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Army National Guard')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Coast Guard')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Coast Guard Reserve')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Marine Corps')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Marine Corps Reserve')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Navy')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Navy Reserve')