-- add military branches
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Air Force')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Air Force Reserve')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Air National Guard')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Army')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Army Reserve')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Army National Guard')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Coast Guard')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Coast Guard Reserve')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Marine Corps')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Marine Corps Reserve')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Navy')
INSERT INTO MilitaryBranches(Country, BranchName) VALUES ('USA', 'Navy Reserve')

-- add government programs
INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
  VALUES  ( N'Illinois All Kids (CHIPRA)' , -- Name - nvarchar(max)
            NULL , -- MinAge - int
            19 , -- MaxAge - int
            NULL , -- MinIncome - money
            NULL , -- MaxIncome - money
            N'State' , -- Tier - nvarchar(128)
            N'USA - Illinois'  -- Locality - nvarchar(128)
          )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Illinois Food Stamp Program' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'State' , -- Tier - nvarchar(128)
              N'USA - Illinois'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Illinois Low Income Home Energy Assistance Program' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'State' , -- Tier - nvarchar(128)
              N'USA - Illinois'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Illinois Medicaid' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              19 , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'State' , -- Tier - nvarchar(128)
              N'USA - Illinois'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Illinois Special Supplemental Nutrition Program for Women, Infants, and Children (WIC)' , -- Name - nvarchar(max)
              0 , -- MinAge - int
              5 , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'State' , -- Tier - nvarchar(128)
              N'USA - Illinois'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Illinois Temporary Assistance for Needy Families (TANF)' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'State' , -- Tier - nvarchar(128)
              N'USA - Illinois'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Illinois Unemployment Insurance' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'State' , -- Tier - nvarchar(128)
              N'USA - Illinois'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Illinois Weatherization Assistance Program' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'State' , -- Tier - nvarchar(128)
              N'USA - Illinois'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'EarnFare' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'State' , -- Tier - nvarchar(128)
              N'USA - Illinois'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Government Housing' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'Municipal' , -- Tier - nvarchar(128)
              N'USA - Illinois - Cook - Chicago'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'LinkCard' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'Municipal' , -- Tier - nvarchar(128)
              N'USA - Illinois - Cook - Chicago'  -- Locality - nvarchar(128)
            )
	INSERT INTO dbo.GovernmentPrograms ( Name , MinAge , MaxAge , MinIncome , MaxIncome , Tier , Locality )
    VALUES  ( N'Supplemental Security Income (SSI)' , -- Name - nvarchar(max)
              NULL , -- MinAge - int
              NULL , -- MaxAge - int
              NULL , -- MinIncome - money
              NULL , -- MaxIncome - money
              N'Federal' , -- Tier - nvarchar(128)
              N'USA'  -- Locality - nvarchar(128)
            )

-- skills
INSERT INTO dbo.Skills
        ( Name )
VALUES  ( N'Soft Skills'  -- Name - nvarchar(max)
          )

-- interests
--INSERT INTO Interests(Name) VALUES ('Aircraft Spotting')
--INSERT INTO Interests(Name) VALUES ('Airbrushing')
--INSERT INTO Interests(Name) VALUES ('Airsofting')
--INSERT INTO Interests(Name) VALUES ('Acting')
--INSERT INTO Interests(Name) VALUES ('Aeromodeling')
--INSERT INTO Interests(Name) VALUES ('Amateur Astronomy')
--INSERT INTO Interests(Name) VALUES ('Amateur Radio')
--INSERT INTO Interests(Name) VALUES ('Animals/pets/dogs')
--INSERT INTO Interests(Name) VALUES ('Archery')
--INSERT INTO Interests(Name) VALUES ('Arts')
--INSERT INTO Interests(Name) VALUES ('Aquarium (Freshwater & Saltwater)')
--INSERT INTO Interests(Name) VALUES ('Astrology')
--INSERT INTO Interests(Name) VALUES ('Astronomy')
--INSERT INTO Interests(Name) VALUES ('Backgammon')
--INSERT INTO Interests(Name) VALUES ('Badminton')
--INSERT INTO Interests(Name) VALUES ('Baseball')
--INSERT INTO Interests(Name) VALUES ('Base Jumping')
--INSERT INTO Interests(Name) VALUES ('Basketball')
--INSERT INTO Interests(Name) VALUES ('Beach/Sun tanning')
--INSERT INTO Interests(Name) VALUES ('Beachcombing')
--INSERT INTO Interests(Name) VALUES ('Beadwork')
--INSERT INTO Interests(Name) VALUES ('Beatboxing')
--INSERT INTO Interests(Name) VALUES ('Becoming A Child Advocate')
--INSERT INTO Interests(Name) VALUES ('Bell Ringing')
--INSERT INTO Interests(Name) VALUES ('Belly Dancing')
--INSERT INTO Interests(Name) VALUES ('Bicycling')
--INSERT INTO Interests(Name) VALUES ('Bicycle Polo')
--INSERT INTO Interests(Name) VALUES ('Bird watching')
--INSERT INTO Interests(Name) VALUES ('Birding')
--INSERT INTO Interests(Name) VALUES ('BMX')
--INSERT INTO Interests(Name) VALUES ('Blacksmithing')
--INSERT INTO Interests(Name) VALUES ('Blogging')
--INSERT INTO Interests(Name) VALUES ('BoardGames')
--INSERT INTO Interests(Name) VALUES ('Boating')
--INSERT INTO Interests(Name) VALUES ('Body Building')
--INSERT INTO Interests(Name) VALUES ('Bonsai Tree')
--INSERT INTO Interests(Name) VALUES ('Bookbinding')
--INSERT INTO Interests(Name) VALUES ('Boomerangs')
--INSERT INTO Interests(Name) VALUES ('Bowling')
--INSERT INTO Interests(Name) VALUES ('Brewing Beer')
--INSERT INTO Interests(Name) VALUES ('Bridge Building')
--INSERT INTO Interests(Name) VALUES ('Bringing Food To The Disabled')
--INSERT INTO Interests(Name) VALUES ('Building A House For Habitat For Humanity')
--INSERT INTO Interests(Name) VALUES ('Building Dollhouses')
--INSERT INTO Interests(Name) VALUES ('Butterfly Watching')
--INSERT INTO Interests(Name) VALUES ('Button Collecting')
--INSERT INTO Interests(Name) VALUES ('Cake Decorating')
--INSERT INTO Interests(Name) VALUES ('Calligraphy')
--INSERT INTO Interests(Name) VALUES ('Camping')
--INSERT INTO Interests(Name) VALUES ('Candle Making')
--INSERT INTO Interests(Name) VALUES ('Canoeing')
--INSERT INTO Interests(Name) VALUES ('Cartooning')
--INSERT INTO Interests(Name) VALUES ('Car Racing')
--INSERT INTO Interests(Name) VALUES ('Casino Gambling')
--INSERT INTO Interests(Name) VALUES ('Cave Diving')
--INSERT INTO Interests(Name) VALUES ('Ceramics')
--INSERT INTO Interests(Name) VALUES ('Cheerleading')
--INSERT INTO Interests(Name) VALUES ('Chess')
--INSERT INTO Interests(Name) VALUES ('Church/church activities')
--INSERT INTO Interests(Name) VALUES ('Cigar Smoking')
--INSERT INTO Interests(Name) VALUES ('Cloud Watching')
--INSERT INTO Interests(Name) VALUES ('Coin Collecting')
--INSERT INTO Interests(Name) VALUES ('Collecting')
--INSERT INTO Interests(Name) VALUES ('Collecting Antiques')
--INSERT INTO Interests(Name) VALUES ('Collecting Artwork')
--INSERT INTO Interests(Name) VALUES ('Collecting Hats')
--INSERT INTO Interests(Name) VALUES ('Collecting Music Albums')
--INSERT INTO Interests(Name) VALUES ('Collecting RPM Records')
--INSERT INTO Interests(Name) VALUES ('Collecting Sports Cards (Baseball, Football, Basketball, Hockey)')
--INSERT INTO Interests(Name) VALUES ('Collecting Swords')
--INSERT INTO Interests(Name) VALUES ('Coloring')
--INSERT INTO Interests(Name) VALUES ('Compose Music')
--INSERT INTO Interests(Name) VALUES ('Computer activities')
--INSERT INTO Interests(Name) VALUES ('Conworlding')
--INSERT INTO Interests(Name) VALUES ('Cooking')
--INSERT INTO Interests(Name) VALUES ('Cosplay')
--INSERT INTO Interests(Name) VALUES ('Crafts')
--INSERT INTO Interests(Name) VALUES ('Crafts (unspecified)')
--INSERT INTO Interests(Name) VALUES ('Crochet')
--INSERT INTO Interests(Name) VALUES ('Crocheting')
--INSERT INTO Interests(Name) VALUES ('Cross-Stitch')
--INSERT INTO Interests(Name) VALUES ('Crossword Puzzles')
--INSERT INTO Interests(Name) VALUES ('Dancing')
--INSERT INTO Interests(Name) VALUES ('Darts')
--INSERT INTO Interests(Name) VALUES ('Diecast Collectibles')
--INSERT INTO Interests(Name) VALUES ('Digital Photography')
--INSERT INTO Interests(Name) VALUES ('Dodgeball')
--INSERT INTO Interests(Name) VALUES ('Dolls')
--INSERT INTO Interests(Name) VALUES ('Dominoes')
--INSERT INTO Interests(Name) VALUES ('Drawing')
--INSERT INTO Interests(Name) VALUES ('Dumpster Diving')
--INSERT INTO Interests(Name) VALUES ('Eating out')
--INSERT INTO Interests(Name) VALUES ('Educational Courses')
--INSERT INTO Interests(Name) VALUES ('Electronics')
--INSERT INTO Interests(Name) VALUES ('Embroidery')
--INSERT INTO Interests(Name) VALUES ('Entertaining')
--INSERT INTO Interests(Name) VALUES ('Exercise (aerobics, weights)')
--INSERT INTO Interests(Name) VALUES ('Falconry')
--INSERT INTO Interests(Name) VALUES ('Fast cars')
--INSERT INTO Interests(Name) VALUES ('Felting')
--INSERT INTO Interests(Name) VALUES ('Fencing')
--INSERT INTO Interests(Name) VALUES ('Fire Poi')
--INSERT INTO Interests(Name) VALUES ('Fishing')
--INSERT INTO Interests(Name) VALUES ('Floorball')
--INSERT INTO Interests(Name) VALUES ('Floral Arrangements')
--INSERT INTO Interests(Name) VALUES ('Fly Tying')
--INSERT INTO Interests(Name) VALUES ('Football')
--INSERT INTO Interests(Name) VALUES ('Four Wheeling')
--INSERT INTO Interests(Name) VALUES ('Freshwater Aquariums')
--INSERT INTO Interests(Name) VALUES ('Frisbee Golf – Frolf')
--INSERT INTO Interests(Name) VALUES ('Games')
--INSERT INTO Interests(Name) VALUES ('Gardening')
--INSERT INTO Interests(Name) VALUES ('Garage Saleing')
--INSERT INTO Interests(Name) VALUES ('Genealogy')
--INSERT INTO Interests(Name) VALUES ('Geocaching')
--INSERT INTO Interests(Name) VALUES ('Ghost Hunting')
--INSERT INTO Interests(Name) VALUES ('Glowsticking')
--INSERT INTO Interests(Name) VALUES ('Gnoming')
--INSERT INTO Interests(Name) VALUES ('Going to movies')
--INSERT INTO Interests(Name) VALUES ('Golf')
--INSERT INTO Interests(Name) VALUES ('Go Kart Racing')
--INSERT INTO Interests(Name) VALUES ('Grip Strength')
--INSERT INTO Interests(Name) VALUES ('Guitar')
--INSERT INTO Interests(Name) VALUES ('Gunsmithing')
--INSERT INTO Interests(Name) VALUES ('Gun Collecting')
--INSERT INTO Interests(Name) VALUES ('Gymnastics')
--INSERT INTO Interests(Name) VALUES ('Gyotaku')
--INSERT INTO Interests(Name) VALUES ('Handwriting Analysis')
--INSERT INTO Interests(Name) VALUES ('Hang gliding')
--INSERT INTO Interests(Name) VALUES ('Herping')
--INSERT INTO Interests(Name) VALUES ('Hiking')
--INSERT INTO Interests(Name) VALUES ('Home Brewing')
--INSERT INTO Interests(Name) VALUES ('Home Repair')
--INSERT INTO Interests(Name) VALUES ('Home Theater')
--INSERT INTO Interests(Name) VALUES ('Horse riding')
--INSERT INTO Interests(Name) VALUES ('Hot air ballooning')
--INSERT INTO Interests(Name) VALUES ('Hula Hooping')
--INSERT INTO Interests(Name) VALUES ('Hunting')
--INSERT INTO Interests(Name) VALUES ('Iceskating')
--INSERT INTO Interests(Name) VALUES ('Illusion')
--INSERT INTO Interests(Name) VALUES ('Impersonations')
--INSERT INTO Interests(Name) VALUES ('Internet')
--INSERT INTO Interests(Name) VALUES ('Inventing')
--INSERT INTO Interests(Name) VALUES ('Jet Engines')
--INSERT INTO Interests(Name) VALUES ('Jewelry Making')
--INSERT INTO Interests(Name) VALUES ('Jigsaw Puzzles')
--INSERT INTO Interests(Name) VALUES ('Juggling')
--INSERT INTO Interests(Name) VALUES ('Keep A Journal')
--INSERT INTO Interests(Name) VALUES ('Jump Roping')
--INSERT INTO Interests(Name) VALUES ('Kayaking')
--INSERT INTO Interests(Name) VALUES ('Kitchen Chemistry')
--INSERT INTO Interests(Name) VALUES ('Kites')
--INSERT INTO Interests(Name) VALUES ('Kite Boarding')
--INSERT INTO Interests(Name) VALUES ('Knitting')
--INSERT INTO Interests(Name) VALUES ('Knotting')
--INSERT INTO Interests(Name) VALUES ('Lasers')
--INSERT INTO Interests(Name) VALUES ('Lawn Darts')
--INSERT INTO Interests(Name) VALUES ('Learn to Play Poker')
--INSERT INTO Interests(Name) VALUES ('Learning A Foreign Language')
--INSERT INTO Interests(Name) VALUES ('Learning An Instrument')
--INSERT INTO Interests(Name) VALUES ('Learning To Pilot A Plane')
--INSERT INTO Interests(Name) VALUES ('Leathercrafting')
--INSERT INTO Interests(Name) VALUES ('Legos')
--INSERT INTO Interests(Name) VALUES ('Letterboxing')
--INSERT INTO Interests(Name) VALUES ('Listening to music')
--INSERT INTO Interests(Name) VALUES ('Locksport')
--INSERT INTO Interests(Name) VALUES ('Lacrosse')
--INSERT INTO Interests(Name) VALUES ('Macramé')
--INSERT INTO Interests(Name) VALUES ('Magic')
--INSERT INTO Interests(Name) VALUES ('Making Model Cars')
--INSERT INTO Interests(Name) VALUES ('Marksmanship')
--INSERT INTO Interests(Name) VALUES ('Martial Arts')
--INSERT INTO Interests(Name) VALUES ('Matchstick Modeling')
--INSERT INTO Interests(Name) VALUES ('Meditation')
--INSERT INTO Interests(Name) VALUES ('Microscopy')
--INSERT INTO Interests(Name) VALUES ('Metal Detecting')
--INSERT INTO Interests(Name) VALUES ('Model Railroading')
--INSERT INTO Interests(Name) VALUES ('Model Rockets')
--INSERT INTO Interests(Name) VALUES ('Modeling Ships')
--INSERT INTO Interests(Name) VALUES ('Models')
--INSERT INTO Interests(Name) VALUES ('Motorcycles')
--INSERT INTO Interests(Name) VALUES ('Mountain Biking')
--INSERT INTO Interests(Name) VALUES ('Mountain Climbing')
--INSERT INTO Interests(Name) VALUES ('Musical Instruments')
--INSERT INTO Interests(Name) VALUES ('Nail Art')
--INSERT INTO Interests(Name) VALUES ('Needlepoint')
--INSERT INTO Interests(Name) VALUES ('Owning An Antique Car')
--INSERT INTO Interests(Name) VALUES ('Origami')
--INSERT INTO Interests(Name) VALUES ('Painting')
--INSERT INTO Interests(Name) VALUES ('Paintball')
--INSERT INTO Interests(Name) VALUES ('Papermaking')
--INSERT INTO Interests(Name) VALUES ('Papermache')
--INSERT INTO Interests(Name) VALUES ('Parachuting')
--INSERT INTO Interests(Name) VALUES ('Paragliding or Power Paragliding')
--INSERT INTO Interests(Name) VALUES ('Parkour')
--INSERT INTO Interests(Name) VALUES ('People Watching')
--INSERT INTO Interests(Name) VALUES ('Photography')
--INSERT INTO Interests(Name) VALUES ('Piano')
--INSERT INTO Interests(Name) VALUES ('Pinochle')
--INSERT INTO Interests(Name) VALUES ('Pipe Smoking')
--INSERT INTO Interests(Name) VALUES ('Planking')
--INSERT INTO Interests(Name) VALUES ('Playing music')
--INSERT INTO Interests(Name) VALUES ('Playing team sports')
--INSERT INTO Interests(Name) VALUES ('Pole Dancing')
--INSERT INTO Interests(Name) VALUES ('Pottery')
--INSERT INTO Interests(Name) VALUES ('Powerboking')
--INSERT INTO Interests(Name) VALUES ('Protesting')
--INSERT INTO Interests(Name) VALUES ('Puppetry')
--INSERT INTO Interests(Name) VALUES ('Pyrotechnics')
--INSERT INTO Interests(Name) VALUES ('Quilting')
--INSERT INTO Interests(Name) VALUES ('Racing Pigeons')
--INSERT INTO Interests(Name) VALUES ('Rafting')
--INSERT INTO Interests(Name) VALUES ('Railfans')
--INSERT INTO Interests(Name) VALUES ('Rapping')
--INSERT INTO Interests(Name) VALUES ('R/C Boats')
--INSERT INTO Interests(Name) VALUES ('R/C Cars')
--INSERT INTO Interests(Name) VALUES ('R/C Helicopters')
--INSERT INTO Interests(Name) VALUES ('R/C Planes')
--INSERT INTO Interests(Name) VALUES ('Reading')
--INSERT INTO Interests(Name) VALUES ('Reading To The Elderly')
--INSERT INTO Interests(Name) VALUES ('Relaxing')
--INSERT INTO Interests(Name) VALUES ('Renaissance Faire')
--INSERT INTO Interests(Name) VALUES ('Renting movies')
--INSERT INTO Interests(Name) VALUES ('Rescuing Abused Or Abandoned Animals')
--INSERT INTO Interests(Name) VALUES ('Robotics')
--INSERT INTO Interests(Name) VALUES ('Rock Balancing')
--INSERT INTO Interests(Name) VALUES ('Rock Collecting')
--INSERT INTO Interests(Name) VALUES ('Rockets')
--INSERT INTO Interests(Name) VALUES ('Rocking AIDS Babies')
--INSERT INTO Interests(Name) VALUES ('Roleplaying')
--INSERT INTO Interests(Name) VALUES ('Running')
--INSERT INTO Interests(Name) VALUES ('Saltwater Aquariums')
--INSERT INTO Interests(Name) VALUES ('Sand Castles')
--INSERT INTO Interests(Name) VALUES ('Scrapbooking')
--INSERT INTO Interests(Name) VALUES ('Scuba Diving')
--INSERT INTO Interests(Name) VALUES ('Self Defense')
--INSERT INTO Interests(Name) VALUES ('Sewing')
--INSERT INTO Interests(Name) VALUES ('Shark Fishing')
--INSERT INTO Interests(Name) VALUES ('Skeet Shooting')
--INSERT INTO Interests(Name) VALUES ('Skiing')
--INSERT INTO Interests(Name) VALUES ('Shopping')
--INSERT INTO Interests(Name) VALUES ('Singing In Choir')
--INSERT INTO Interests(Name) VALUES ('Skateboarding')
--INSERT INTO Interests(Name) VALUES ('Sketching')
--INSERT INTO Interests(Name) VALUES ('Sky Diving')
--INSERT INTO Interests(Name) VALUES ('Slack Lining')
--INSERT INTO Interests(Name) VALUES ('Sleeping')
--INSERT INTO Interests(Name) VALUES ('Slingshots')
--INSERT INTO Interests(Name) VALUES ('Slot Car Racing')
--INSERT INTO Interests(Name) VALUES ('Snorkeling')
--INSERT INTO Interests(Name) VALUES ('Snowboarding')
--INSERT INTO Interests(Name) VALUES ('Soap Making')
--INSERT INTO Interests(Name) VALUES ('Soccer')
--INSERT INTO Interests(Name) VALUES ('Socializing with friends/neighbors')
--INSERT INTO Interests(Name) VALUES ('Speed Cubing (rubix cube)')
--INSERT INTO Interests(Name) VALUES ('Spelunkering')
--INSERT INTO Interests(Name) VALUES ('Spending time with family/kids')
--INSERT INTO Interests(Name) VALUES ('Stamp Collecting')
--INSERT INTO Interests(Name) VALUES ('Storm Chasing')
--INSERT INTO Interests(Name) VALUES ('Storytelling')
--INSERT INTO Interests(Name) VALUES ('String Figures')
--INSERT INTO Interests(Name) VALUES ('Surfing')
--INSERT INTO Interests(Name) VALUES ('Surf Fishing')
--INSERT INTO Interests(Name) VALUES ('Survival')
--INSERT INTO Interests(Name) VALUES ('Swimming')
--INSERT INTO Interests(Name) VALUES ('Tatting')
--INSERT INTO Interests(Name) VALUES ('Taxidermy')
--INSERT INTO Interests(Name) VALUES ('Tea Tasting')
--INSERT INTO Interests(Name) VALUES ('Tennis')
--INSERT INTO Interests(Name) VALUES ('Tesla Coils')
--INSERT INTO Interests(Name) VALUES ('Tetris')
--INSERT INTO Interests(Name) VALUES ('Texting')
--INSERT INTO Interests(Name) VALUES ('Textiles')
--INSERT INTO Interests(Name) VALUES ('Tombstone Rubbing')
--INSERT INTO Interests(Name) VALUES ('Tool Collecting')
--INSERT INTO Interests(Name) VALUES ('Toy Collecting')
--INSERT INTO Interests(Name) VALUES ('Train Collecting')
--INSERT INTO Interests(Name) VALUES ('Train Spotting')
--INSERT INTO Interests(Name) VALUES ('Traveling')
--INSERT INTO Interests(Name) VALUES ('Treasure Hunting')
--INSERT INTO Interests(Name) VALUES ('Trekkie')
--INSERT INTO Interests(Name) VALUES ('Tutoring Children')
--INSERT INTO Interests(Name) VALUES ('TV watching')
--INSERT INTO Interests(Name) VALUES ('Ultimate Frisbee')
--INSERT INTO Interests(Name) VALUES ('Urban Exploration')
--INSERT INTO Interests(Name) VALUES ('Video Games')
--INSERT INTO Interests(Name) VALUES ('Violin')
--INSERT INTO Interests(Name) VALUES ('Volunteer')
--INSERT INTO Interests(Name) VALUES ('Walking')
--INSERT INTO Interests(Name) VALUES ('Warhammer')
--INSERT INTO Interests(Name) VALUES ('Watching sporting events')
--INSERT INTO Interests(Name) VALUES ('Weather Watcher')
--INSERT INTO Interests(Name) VALUES ('Weightlifting')
--INSERT INTO Interests(Name) VALUES ('Windsurfing')
--INSERT INTO Interests(Name) VALUES ('Wine Making')
--INSERT INTO Interests(Name) VALUES ('Wingsuit Flying')
--INSERT INTO Interests(Name) VALUES ('Woodworking')
--INSERT INTO Interests(Name) VALUES ('Working In A Food Pantry')
--INSERT INTO Interests(Name) VALUES ('Working on cars')
--INSERT INTO Interests(Name) VALUES ('World Record Breaking')
--INSERT INTO Interests(Name) VALUES ('Wrestling')
--INSERT INTO Interests(Name) VALUES ('Writing')
--INSERT INTO Interests(Name) VALUES ('Writing Music')
--INSERT INTO Interests(Name) VALUES ('Writing Songs')
--INSERT INTO Interests(Name) VALUES ('Yoga')
--INSERT INTO Interests(Name) VALUES ('YoYo')
--INSERT INTO Interests(Name) VALUES ('Ziplining')
--INSERT INTO Interests(Name) VALUES ('Zumba')