//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveChicago.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseNote
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public string CaseManagerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> OutcomeId { get; set; }
        public Nullable<decimal> OutcomeWeight { get; set; }
        public Nullable<int> NonprofitId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Member Member { get; set; }
        public virtual Outcome Outcome { get; set; }
    }
}
