//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveChicago.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporationSurvey
    {
        public int Id { get; set; }
        public int SurveyId { get; set; }
        public int CorporationId { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
