//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveChicago.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SolveChicagoEntities : DbContext
    {
        public SolveChicagoEntities()
            : base("name=SolveChicagoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<CaseManager> CaseManagers { get; set; }
        public virtual DbSet<CaseNote> CaseNotes { get; set; }
        public virtual DbSet<Corporation> Corporations { get; set; }
        public virtual DbSet<GovernmentProgram> GovernmentPrograms { get; set; }
        public virtual DbSet<MemberChildren> MemberChildrens { get; set; }
        public virtual DbSet<MemberChildrenGovernmentProgram> MemberChildrenGovernmentPrograms { get; set; }
        public virtual DbSet<MemberCorporation> MemberCorporations { get; set; }
        public virtual DbSet<MemberEmergencyContact> MemberEmergencyContacts { get; set; }
        public virtual DbSet<MemberGovernmentProgram> MemberGovernmentPrograms { get; set; }
        public virtual DbSet<MemberNonprofit> MemberNonprofits { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberStatus> MemberStatuses { get; set; }
        public virtual DbSet<MemberSurvey> MemberSurveys { get; set; }
        public virtual DbSet<Nonprofit> Nonprofits { get; set; }
        public virtual DbSet<Outcome> Outcomes { get; set; }
        public virtual DbSet<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual DbSet<SurveyQuestionOption> SurveyQuestionOptions { get; set; }
        public virtual DbSet<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
