//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveChicago.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMilitary
    {
        public int MemberId { get; set; }
        public int MilitaryId { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string LastPayGrade { get; set; }
        public string CurrentStatus { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual MilitaryBranch MilitaryBranch { get; set; }
    }
}
