//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveChicago.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonprofitSkill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NonprofitSkill()
        {
            this.MemberSkills = new HashSet<MemberSkill>();
        }
    
        public int Id { get; set; }
        public int NonprofitId { get; set; }
        public int SkillId { get; set; }
        public Nullable<int> ProgramId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSkill> MemberSkills { get; set; }
        public virtual NonprofitProgram NonprofitProgram { get; set; }
        public virtual Nonprofit Nonprofit { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
