//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveChicago.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public int Id { get; set; }
        public int ReferringId { get; set; }
        public int ReferredId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual NonprofitProgram NonprofitProgram { get; set; }
        public virtual Nonprofit Nonprofit { get; set; }
        public virtual Nonprofit Nonprofit1 { get; set; }
    }
}
