//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveChicago.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyAnswer()
        {
            this.CorporationSurveyAnswers = new HashSet<CorporationSurveyAnswer>();
            this.MemberSurveyAnswers = new HashSet<MemberSurveyAnswer>();
        }
    
        public int Id { get; set; }
        public int SurveyId { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
        public string AnswerBatchId { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporationSurveyAnswer> CorporationSurveyAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSurveyAnswer> MemberSurveyAnswers { get; set; }
        public virtual SurveyQuestion SurveyQuestion { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
