CREATE TABLE [dbo].[Surveys]
(
	[Id] INT IDENTITY(1, 1) NOT NULL, 
    [Name] NVARCHAR(128) NOT NULL, 
    [Audience] NVARCHAR(50) NOT NULL,
	[UserId] NVARCHAR(128)  NOT NULL, 

    CONSTRAINT [PK_Surveys] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Surveys_AspNetUser] FOREIGN KEY (UserId) REFERENCES [AspNetUser](Id) ON DELETE CASCADE,
)
