//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveChicago.App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberStatus
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
